title:              Facu Castella Blog
email:              facucaste96@gmail.com
description:        A Blog by Facu Castella, focused on Data Analytics and other stuff as well
author:             Facu Castella
baseurl:            ""
url:                "https://Facucastella.github.io"

# Social Profiles
twitter_username:   facucaste96
github_username:    Facucastella
facebook_username:  
instagram_username:  facucastella
linkedin_username: Facundo Castella

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
